name: Update Peilingwijzer data
 
on:
  schedule:
    - cron:  '0 17 * * *'  # 17:00 UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        # below options prescribed by example here: https://github.com/marketplace/actions/github-push#example-workflow-file
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.2'
      - name: install dependencies
        run: pip install -r requirements_update.txt
      - name: run update script
        run: ./update_numbers.sh
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

